[theme]
base = "light"
primaryColor = "#98FB98"
backgroundColor = "#E0FFFF"
secondaryBackgroundColor = "#2D6A4F"
textColor = "#1E293B"

font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false